project:
  type: website
  output-dir: docs
  resources:
    - CNAME

format:
  html:
    # theme: 
    #   dark: [dark, atom-one-dark.scss]
    #   light: light
    # highlight-style: atom-one-dark
    css: styles.css
    toc: true
    googlefonts: false

website:
  title: "CSC 222 Systems Programming"
  site-url: https://csc222.jcor.dev
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "0 - Housekeeping"
        contents: 
          - 00 Housekeeping/01 Syllabus.qmd

      - section: "1 - Linux"
        href: "01 Linux/index.qmd"
        contents:
          - 01 Linux/01 A Brief History.qmd
          - section: "VM Install"
            contents: 
              - 01 Linux/02 VM Install/01 Overview.qmd
              - 01 Linux/02 VM Install/02 Virtualization Software Install.qmd
              - 01 Linux/02 VM Install/03 Download an Image.qmd
              - 01 Linux/02 VM Install/04 Creating the VM.qmd
              - 01 Linux/02 VM Install/05 Installing the VM.qmd
              - 01 Linux/02 VM Install/06 Creating a Shared Folder.qmd
              - 01 Linux/02 VM Install/07 Installing Tools on VM.qmd
          - 01 Linux/linux-filesystem.qmd
          # - linux/vm-install-win.qmd
          # - linux/vm-install-mac.qmd
          # - linux/additional-steps.qmd


      - section: "2 - Terminal and Shell"
        href: "02 Terminal and Shell/index.html"
        contents:
          - 02 Terminal and Shell/00 Background.qmd
          - 02 Terminal and Shell/01 Basic Commands.qmd
          - 02 Terminal and Shell/02 Working With Files.qmd
          - 02 Terminal and Shell/03 Other Useful Tips.qmd
          - 02 Terminal and Shell/04 Redirection.qmd
          - 02 Terminal and Shell/05 File Permissions.qmd
          - 02 Terminal and Shell/06 Grep and Regex.qmd


      - section: "3 - C Programming"
        href: "03 C Programming/index.qmd"
        contents:
          - 03 C Programming/01-HelloWorld.qmd
          - 03 C Programming/02-DataTypes.qmd
          - 03 C Programming/03-Operators.qmd
          - 03 C Programming/04-Functions.qmd
          - 03 C Programming/05-More-on-Data.qmd
          - 03 C Programming/06-Sample-Applications.qmd
          - 03 C Programming/07-Memory-Allocation.qm4
          - 03 C Programming/08-Structs-and-Unions.qmd
          - 03 C Programming/09-Sample-Applications.qmd


      - section: "4 - Computing Systems and Data Representation"
        href: "04 Computing Systems and Data Representation/index.qmd"
        contents: 
          - 04 Computing Systems and Data Representation/01 Computing Systems.qmd
          - 04 Computing Systems and Data Representation/02 The Compilation Process.qmd
          - 04 Computing Systems and Data Representation/03 Representing Programs.qmd
          - 04 Computing Systems and Data Representation/04 Data in a System.qmd
          - 04 Computing Systems and Data Representation/05 Binary and Hex.qmd
          - 04 Computing Systems and Data Representation/06 Bitwise Operations.qmd
          - 04 Computing Systems and Data Representation/07 Logical Operations at the Bit Level.qmd
          - 04 Computing Systems and Data Representation/08 Bit Shifting.qmd
          - 04 Computing Systems and Data Representation/09 Sign Extension.qmd
          - 04 Computing Systems and Data Representation/10 Power of Two Operations.qmd
          - 04 Computing Systems and Data Representation/11 Fractional Binary.qmd
          - 04 Computing Systems and Data Representation/12 IEEE 754 Values.qmd



      - section: "5 - System Calls"
        href: "05 System Calls/index.qmd"
        contents:
          - "05 System Calls/00 Overview.qmd"
          - "05 System Calls/01 Using Syscall.qmd"
          - "05 System Calls/02 Fork and Wait.qmd"
          - "05 System Calls/03 Exec Functions.qmd"
          - "05 System Calls/04 Working with Files.qmd"
          - "05 System Calls/05 Dup2.qmd"
          - "05 System Calls/06 Piping.qmd"
          - "05 System Calls/07 Signals.qmd"

      - section: "6 - Bash Scripting"
        href: "06 Bash Scripting/index.qmd"
        contents:
          - 06 Bash Scripting/01-Intro.qmd
          - 06 Bash Scripting/02-Args.qmd
          - 06 Bash Scripting/03-Conditionals.qmd
          - 06 Bash Scripting/04-Exit-Codes.qmd
          - 06 Bash Scripting/05-Case.qmd
          - 06 Bash Scripting/06-Loops.qmd
          - 06 Bash Scripting/07-Functions.qmd

      - section: "7 - Assembly Primer"
        href: "07 Assembly Primer/index.qmd"
        contents:
          - 07 Assembly Primer/00 Overview.qmd
          - 07 Assembly Primer/01 Hello World.qmd
          - 07 Assembly Primer/02 File Sections.qmd
          - 07 Assembly Primer/03 Variables.qmd
          - 07 Assembly Primer/04 The Stack.qmd
          # - 07 Assembly Primer/06 The Load Effective Address Instruction.qmd
          # - 07 Assembly Primer/07 Status Flags.qmd
          # - 07 Assembly Primer/08 Arithmetic Instructions.qmd
          # - 07 Assembly Primer/09 Comparing and Jumps.qmd
          # - 07 Assembly Primer/10 Reverse Engineering with C.qmd









