---
title: Downloading An Image
---


## Flavors of Linux

For this course it is recommended that you use Mint or Ubuntu, although there are many more flavors of Linux available. Below is a very short list of the distros that most of you will either use or become familiar with eventually.

1. Ubuntu is designed with beginners in mind. It is a general purpose distro with both server and desktop environments. It is also the most popular distribution.

2. Linux mint is based on Ubuntu and is good for beginners who are switching from windows. This is because it is designed to be familiar for
windows users.

3. Debian is one of the oldest distros and is typically used where stability is paramount. It is used by experienced users and is popular for servers and mission critical environments.

4. Arch linux is used by advanced users for whom customization and minimalist systems are important. Users of this system typically want to be involved in manually setting up everything on the computer.

5. Kali linux is based on debian and is used by cyber security professionals. This is because it comes with multiple tools for penetration testing, forensics and security research

6. Raspbian is a version of linux designed to work on raspberry pis. The focus of this distro is being light weight (i.e. not taking up a lot of space), and yet work fast with the limited hardware resources one might find on a microcomputer like a raspberry pi


## Downloading an ISO

In order to install a guest operating system with Virtual Box, you'll want a `.iso` file that contains the image of the guest OS. Follow the `.iso` download instructions that are most appropriate for your machine.


### For Mac Users

If you have an **Apple Silicon** based Mac, download the latest [LTS for Ubuntu](https://ubuntu.com/download/desktop). Be aware that we're encouraging non-arm based machines to use [Linux Mint](https://www.linuxmint.com/download.php) for their builds to have as many people as possible on the same OS, however there is no out of the box arm based version of Mint, thus Ubuntu Desktop is the way to go.

If you have an **Intel** based Mac, it is recommended that you choose [Linux Mint](https://www.linuxmint.com/download.php) for this course and CSC 442.

Once you have downloaded the `.iso` file, move the downloaded file to the folder you have created for this course on your computer so you can easily find it when you need it later.

::: {.callout-tip}
# Apple Silicon or Intel?

Not sure what type of Mac you have? Click the Apple icon in the top left corner of your screen and select "About This Mac". If the chip is one of the m-series chips (m1, m2, etc.), then you have an Apple Silicon based machine.
:::


### For Linux Users

If you have an **x86-64/amd64** based machine, choose between either of the following. If you use Ubuntu regularly, try Mint, if you use Mint, try Ubuntu. If you're a Linux user and you want to try Arch or a non GNU/Linux based distro, go for it, just know that support for this course will be limited to Ubuntu and Mint.

- [Linux Mint](https://www.linuxmint.com/download.php)
- [Ubuntu Desktop](https://ubuntu.com/download/desktop)

Once you have downloaded the `.iso` file, move the file to the folder you have created for this course on your computer so you can easily find it when you need it later.

::: {.callout-note}
# I already use Linux, so why?

You might be wondering, "I already use a GNU/Linux environment? Why do I need to install a VM?" 

We just need to make sure this is a skill you have and understand. Most of the work/programs for this course can be completed on any Unix-Like environemnt.

Also, perhaps there is software we will install that you don't necessarily want on your host, this will create an environment for you to modify that wont affect your host.
:::


### For Windows Users

If you have an **x86-64/amd64** based machine, you're encouraged to use Linux Mint for CSC 222 and CSC 442:

- [Linux Mint](https://www.linuxmint.com/download.php)
- [Ubuntu Desktop](https://ubuntu.com/download/desktop)

Once you have downloaded the `.iso` file, move the file to the folder you have created for this course on your computer so you can easily find it when you need it later.

